-- =============================================================
-- Dr. Serap Uysal Initial Schema
-- =============================================================
-- =============================================================
-- Dr. Serap Uysal Initial Schema - ROLLBACK
-- =============================================================

-- ---------------------------------------------------------------
-- ROLE_PERMISSION ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_ROLE_PERMISSION_HIS ON drserapuysal.ROLE_PERMISSION;
DROP FUNCTION IF EXISTS drserapuysal.FN_ROLE_PERMISSION_HIS();
DROP INDEX IF EXISTS drserapuysal.IDX_ROLE_PERMISSION_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS drserapuysal.ROLE_PERMISSION_HIS;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_ROLE_PERMISSION_HIS;
DROP INDEX IF EXISTS drserapuysal.IDX_ROLE_PERMISSION_ROLE_ID;
DROP INDEX IF EXISTS drserapuysal.IDX_ROLE_PERMISSION_PERMISSION_ID;
DROP TABLE IF EXISTS drserapuysal.ROLE_PERMISSION;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_ROLE_PERMISSION;

-- ---------------------------------------------------------------
-- USERS_ROLE ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_USERS_ROLE_HIS ON drserapuysal.USERS_ROLE;
DROP FUNCTION IF EXISTS drserapuysal.FN_USERS_ROLE_HIS();
DROP INDEX IF EXISTS drserapuysal.IDX_USERS_ROLE_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS drserapuysal.USERS_ROLE_HIS;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_USERS_ROLE_HIS;
DROP INDEX IF EXISTS drserapuysal.IDX_USERS_ROLE_USERS_ID;
DROP INDEX IF EXISTS drserapuysal.IDX_USERS_ROLE_ROLE_ID;
DROP TABLE IF EXISTS drserapuysal.USERS_ROLE;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_USERS_ROLE;

-- ---------------------------------------------------------------
-- PERMISSION ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_PERMISSION_HIS ON drserapuysal.PERMISSION;
DROP FUNCTION IF EXISTS drserapuysal.FN_PERMISSION_HIS();
DROP INDEX IF EXISTS drserapuysal.IDX_PERMISSION_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS drserapuysal.PERMISSION_HIS;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_PERMISSION_HIS;
DROP INDEX IF EXISTS drserapuysal.IDX_PERMISSION_NAME;
DROP INDEX IF EXISTS drserapuysal.IDX_PERMISSION_MODULE;
DROP INDEX IF EXISTS drserapuysal.IDX_PERMISSION_ACTION;
DROP INDEX IF EXISTS drserapuysal.IDX_PERMISSION_STATUS;
DROP TABLE IF EXISTS drserapuysal.PERMISSION;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_PERMISSION;

-- ---------------------------------------------------------------
-- ROLE ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_ROLE_HIS ON drserapuysal.ROLE;
DROP FUNCTION IF EXISTS drserapuysal.FN_ROLE_HIS();
DROP INDEX IF EXISTS drserapuysal.IDX_ROLE_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS drserapuysal.ROLE_HIS;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_ROLE_HIS;
DROP INDEX IF EXISTS drserapuysal.IDX_ROLE_NAME;
DROP INDEX IF EXISTS drserapuysal.IDX_ROLE_STATUS;
DROP TABLE IF EXISTS drserapuysal.ROLE;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_ROLE;

-- ---------------------------------------------------------------
-- USERS ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_USERS_HIS ON drserapuysal.USERS;
DROP FUNCTION IF EXISTS drserapuysal.FN_USERS_HIS();
DROP INDEX IF EXISTS drserapuysal.IDX_USERS_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS drserapuysal.USERS_HIS;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_USERS_HIS;
DROP INDEX IF EXISTS drserapuysal.IDX_USERS_USERNAME;
DROP INDEX IF EXISTS drserapuysal.IDX_USERS_EMAIL;
DROP INDEX IF EXISTS drserapuysal.IDX_USERS_STATUS;
DROP TABLE IF EXISTS drserapuysal.USERS;
DROP SEQUENCE IF EXISTS drserapuysal.SEQ_USERS;

-- ---------------------------------------------------------------
-- SCHEMA
-- ---------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS drserapuysal;

-- ---------------------------------------------------------------
-- USERS
-- ---------------------------------------------------------------
CREATE SEQUENCE drserapuysal.SEQ_USERS START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.USERS (
    ID                  BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_USERS'),
    USERNAME            VARCHAR(100)    NOT NULL,
    EMAIL               VARCHAR(150)    NOT NULL,
    PASSWORD_HASH       VARCHAR(255)    NOT NULL,
    FIRST_NAME          VARCHAR(100)    NOT NULL,
    LAST_NAME           VARCHAR(100)    NOT NULL,
    PHONE               VARCHAR(20),
    STATUS              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    LAST_LOGIN_DATE     TIMESTAMP,
    ERROR_LOGIN_COUNT   INTEGER         NOT NULL DEFAULT 0,
    CREATED_BY          VARCHAR(100)    NOT NULL,
    CREATED_DATE        TIMESTAMP       NOT NULL,
    CREATED_IP          VARCHAR(45)     NOT NULL,
    UPDATED_BY          VARCHAR(100),
    UPDATED_DATE        TIMESTAMP,
    UPDATED_IP          VARCHAR(45),
    CONSTRAINT PK_USERS          PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL    UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_STATUS   CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);

CREATE INDEX IDX_USERS_USERNAME ON drserapuysal.USERS (USERNAME);
CREATE INDEX IDX_USERS_EMAIL    ON drserapuysal.USERS (EMAIL);
CREATE INDEX IDX_USERS_STATUS   ON drserapuysal.USERS (STATUS);

CREATE SEQUENCE drserapuysal.SEQ_USERS_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.USERS_HIS (
    ID                  BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_USERS_HIS'),
    ORIGINAL_ID         BIGINT          NOT NULL,
    USERNAME            VARCHAR(100)    NOT NULL,
    EMAIL               VARCHAR(150)    NOT NULL,
    PASSWORD_HASH       VARCHAR(255)    NOT NULL,
    FIRST_NAME          VARCHAR(100)    NOT NULL,
    LAST_NAME           VARCHAR(100)    NOT NULL,
    PHONE               VARCHAR(20),
    STATUS              VARCHAR(20)     NOT NULL,
    LAST_LOGIN_DATE     TIMESTAMP,
    ERROR_LOGIN_COUNT   INTEGER         NOT NULL,
    CREATED_BY          VARCHAR(100)    NOT NULL,
    CREATED_DATE        TIMESTAMP       NOT NULL,
    CREATED_IP          VARCHAR(45)     NOT NULL,
    UPDATED_BY          VARCHAR(100),
    UPDATED_DATE        TIMESTAMP,
    UPDATED_IP          VARCHAR(45),
    DML_OPERATION       VARCHAR(10),
    DML_BY              VARCHAR(100),
    DML_DATE            TIMESTAMP,
    DML_IP              VARCHAR(45),
    CONSTRAINT PK_USERS_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_USERS_HIS_ORIGINAL_ID ON drserapuysal.USERS_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION drserapuysal.FN_USERS_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO drserapuysal.USERS_HIS (
            ID, ORIGINAL_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME,
            PHONE, STATUS, LAST_LOGIN_DATE, ERROR_LOGIN_COUNT,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_USERS_HIS'), NEW.ID, NEW.USERNAME, NEW.EMAIL, NEW.PASSWORD_HASH, NEW.FIRST_NAME, NEW.LAST_NAME,
            NEW.PHONE, NEW.STATUS, NEW.LAST_LOGIN_DATE, NEW.ERROR_LOGIN_COUNT,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO drserapuysal.USERS_HIS (
            ID, ORIGINAL_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME,
            PHONE, STATUS, LAST_LOGIN_DATE, ERROR_LOGIN_COUNT,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_USERS_HIS'), NEW.ID, NEW.USERNAME, NEW.EMAIL, NEW.PASSWORD_HASH, NEW.FIRST_NAME, NEW.LAST_NAME,
            NEW.PHONE, NEW.STATUS, NEW.LAST_LOGIN_DATE, NEW.ERROR_LOGIN_COUNT,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO drserapuysal.USERS_HIS (
            ID, ORIGINAL_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME,
            PHONE, STATUS, LAST_LOGIN_DATE, ERROR_LOGIN_COUNT,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_USERS_HIS'), OLD.ID, OLD.USERNAME, OLD.EMAIL, OLD.PASSWORD_HASH, OLD.FIRST_NAME, OLD.LAST_NAME,
            OLD.PHONE, OLD.STATUS, OLD.LAST_LOGIN_DATE, OLD.ERROR_LOGIN_COUNT,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_USERS_HIS
    AFTER INSERT OR UPDATE OR DELETE ON drserapuysal.USERS
    FOR EACH ROW EXECUTE FUNCTION drserapuysal.FN_USERS_HIS();


-- ---------------------------------------------------------------
-- ROLE
-- ---------------------------------------------------------------
CREATE SEQUENCE drserapuysal.SEQ_ROLE START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.ROLE (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_ROLE'),
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_ROLE        PRIMARY KEY (ID),
    CONSTRAINT UK_ROLE_NAME   UNIQUE (NAME),
    CONSTRAINT CK_ROLE_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IDX_ROLE_NAME   ON drserapuysal.ROLE (NAME);
CREATE INDEX IDX_ROLE_STATUS ON drserapuysal.ROLE (STATUS);

CREATE SEQUENCE drserapuysal.SEQ_ROLE_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.ROLE_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_ROLE_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_ROLE_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_ROLE_HIS_ORIGINAL_ID ON drserapuysal.ROLE_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION drserapuysal.FN_ROLE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO drserapuysal.ROLE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_ROLE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO drserapuysal.ROLE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_ROLE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO drserapuysal.ROLE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_ROLE_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_ROLE_HIS
    AFTER INSERT OR UPDATE OR DELETE ON drserapuysal.ROLE
    FOR EACH ROW EXECUTE FUNCTION drserapuysal.FN_ROLE_HIS();


-- ---------------------------------------------------------------
-- PERMISSION
-- ---------------------------------------------------------------
CREATE SEQUENCE drserapuysal.SEQ_PERMISSION START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.PERMISSION (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_PERMISSION'),
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE          VARCHAR(100)    NOT NULL,
    ACTION          VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_PERMISSION                PRIMARY KEY (ID),
    CONSTRAINT UK_PERMISSION_NAME           UNIQUE (NAME),
    CONSTRAINT UK_PERMISSION_MODULE_ACTION  UNIQUE (MODULE, ACTION),
    CONSTRAINT CK_PERMISSION_STATUS         CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_PERMISSION_ACTION         CHECK (ACTION IN ('CREATE', 'READ', 'UPDATE', 'DELETE', 'LIST', 'EXPORT', 'IMPORT'))
);

CREATE INDEX IDX_PERMISSION_NAME   ON drserapuysal.PERMISSION (NAME);
CREATE INDEX IDX_PERMISSION_MODULE ON drserapuysal.PERMISSION (MODULE);
CREATE INDEX IDX_PERMISSION_ACTION ON drserapuysal.PERMISSION (ACTION);
CREATE INDEX IDX_PERMISSION_STATUS ON drserapuysal.PERMISSION (STATUS);

CREATE SEQUENCE drserapuysal.SEQ_PERMISSION_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.PERMISSION_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_PERMISSION_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE          VARCHAR(100)    NOT NULL,
    ACTION          VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_PERMISSION_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_PERMISSION_HIS_ORIGINAL_ID ON drserapuysal.PERMISSION_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION drserapuysal.FN_PERMISSION_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO drserapuysal.PERMISSION_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_PERMISSION_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE, NEW.ACTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO drserapuysal.PERMISSION_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_PERMISSION_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE, NEW.ACTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO drserapuysal.PERMISSION_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_PERMISSION_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.MODULE, OLD.ACTION, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_PERMISSION_HIS
    AFTER INSERT OR UPDATE OR DELETE ON drserapuysal.PERMISSION
    FOR EACH ROW EXECUTE FUNCTION drserapuysal.FN_PERMISSION_HIS();


-- ---------------------------------------------------------------
-- USERS_ROLE
-- ---------------------------------------------------------------
CREATE SEQUENCE drserapuysal.SEQ_USERS_ROLE START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.USERS_ROLE (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_USERS_ROLE'),
    USERS_ID        BIGINT          NOT NULL,
    ROLE_ID         BIGINT          NOT NULL,
    ASSIGNED_BY     VARCHAR(100)    NOT NULL,
    ASSIGNED_DATE   TIMESTAMP       NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_USERS_ROLE             PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_ROLE_USERS_ROLE  UNIQUE (USERS_ID, ROLE_ID),
    CONSTRAINT FK_USERS_ROLE_USERS       FOREIGN KEY (USERS_ID) REFERENCES drserapuysal.USERS(ID),
    CONSTRAINT FK_USERS_ROLE_ROLE        FOREIGN KEY (ROLE_ID)  REFERENCES drserapuysal.ROLE(ID)
);

CREATE INDEX IDX_USERS_ROLE_USERS_ID ON drserapuysal.USERS_ROLE (USERS_ID);
CREATE INDEX IDX_USERS_ROLE_ROLE_ID  ON drserapuysal.USERS_ROLE (ROLE_ID);

CREATE SEQUENCE drserapuysal.SEQ_USERS_ROLE_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.USERS_ROLE_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_USERS_ROLE_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    USERS_ID        BIGINT          NOT NULL,
    ROLE_ID         BIGINT          NOT NULL,
    ASSIGNED_BY     VARCHAR(100)    NOT NULL,
    ASSIGNED_DATE   TIMESTAMP       NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_USERS_ROLE_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_USERS_ROLE_HIS_ORIGINAL_ID ON drserapuysal.USERS_ROLE_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION drserapuysal.FN_USERS_ROLE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO drserapuysal.USERS_ROLE_HIS (
            ID, ORIGINAL_ID, USERS_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_USERS_ROLE_HIS'), NEW.ID, NEW.USERS_ID, NEW.ROLE_ID, NEW.ASSIGNED_BY, NEW.ASSIGNED_DATE,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO drserapuysal.USERS_ROLE_HIS (
            ID, ORIGINAL_ID, USERS_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_USERS_ROLE_HIS'), NEW.ID, NEW.USERS_ID, NEW.ROLE_ID, NEW.ASSIGNED_BY, NEW.ASSIGNED_DATE,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO drserapuysal.USERS_ROLE_HIS (
            ID, ORIGINAL_ID, USERS_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_USERS_ROLE_HIS'), OLD.ID, OLD.USERS_ID, OLD.ROLE_ID, OLD.ASSIGNED_BY, OLD.ASSIGNED_DATE,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_USERS_ROLE_HIS
    AFTER INSERT OR UPDATE OR DELETE ON drserapuysal.USERS_ROLE
    FOR EACH ROW EXECUTE FUNCTION drserapuysal.FN_USERS_ROLE_HIS();


-- ---------------------------------------------------------------
-- ROLE_PERMISSION
-- ---------------------------------------------------------------
CREATE SEQUENCE drserapuysal.SEQ_ROLE_PERMISSION START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.ROLE_PERMISSION (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_ROLE_PERMISSION'),
    ROLE_ID         BIGINT          NOT NULL,
    PERMISSION_ID   BIGINT          NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_ROLE_PERMISSION                       PRIMARY KEY (ID),
    CONSTRAINT UK_ROLE_PERMISSION_ROLE_PERMISSION       UNIQUE (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_ROLE_PERMISSION_ROLE                  FOREIGN KEY (ROLE_ID)       REFERENCES drserapuysal.ROLE(ID),
    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION            FOREIGN KEY (PERMISSION_ID) REFERENCES drserapuysal.PERMISSION(ID)
);

CREATE INDEX IDX_ROLE_PERMISSION_ROLE_ID       ON drserapuysal.ROLE_PERMISSION (ROLE_ID);
CREATE INDEX IDX_ROLE_PERMISSION_PERMISSION_ID ON drserapuysal.ROLE_PERMISSION (PERMISSION_ID);

CREATE SEQUENCE drserapuysal.SEQ_ROLE_PERMISSION_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE drserapuysal.ROLE_PERMISSION_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('drserapuysal.SEQ_ROLE_PERMISSION_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    ROLE_ID         BIGINT          NOT NULL,
    PERMISSION_ID   BIGINT          NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_ROLE_PERMISSION_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_ROLE_PERMISSION_HIS_ORIGINAL_ID ON drserapuysal.ROLE_PERMISSION_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION drserapuysal.FN_ROLE_PERMISSION_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO drserapuysal.ROLE_PERMISSION_HIS (
            ID, ORIGINAL_ID, ROLE_ID, PERMISSION_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_ROLE_PERMISSION_HIS'), NEW.ID, NEW.ROLE_ID, NEW.PERMISSION_ID,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO drserapuysal.ROLE_PERMISSION_HIS (
            ID, ORIGINAL_ID, ROLE_ID, PERMISSION_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_ROLE_PERMISSION_HIS'), NEW.ID, NEW.ROLE_ID, NEW.PERMISSION_ID,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO drserapuysal.ROLE_PERMISSION_HIS (
            ID, ORIGINAL_ID, ROLE_ID, PERMISSION_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('drserapuysal.SEQ_ROLE_PERMISSION_HIS'), OLD.ID, OLD.ROLE_ID, OLD.PERMISSION_ID,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_ROLE_PERMISSION_HIS
    AFTER INSERT OR UPDATE OR DELETE ON drserapuysal.ROLE_PERMISSION
    FOR EACH ROW EXECUTE FUNCTION drserapuysal.FN_ROLE_PERMISSION_HIS();
